=encoding UTF-8

=head1 NAME

connectivity - Documentation of collectd's C<connectivity plugin>

=head1 SYNOPSIS

  # See collectd.conf(5)
  LoadPlugin connectivity
  # ...
  <Plugin connectivity>
    Interface eth0
  </Plugin>

=head1 DESCRIPTION

The C<connectivity plugin> opens a netlink UNIX-socket over which it receives network interface status events.


=head1 OPERATION

This plugin collects data.

I<Status> 

If I<Status> is greater than or equal to zero the message indicates interface is up,
if I<Status> is less than zero the message indicates interface is down. 

=back

=head1 SEE ALSO

L<collectd(1)>,
L<collectd.conf(5)>

=head1 AUTHOR

The C<connectivity plugin> has been written by Andrew Bays <lt>abays<nbsp>atE<nbsp>redhat.comE<gt>.

This manpage has been written by Aneesh Puttur E<lt>aputtur<nbsp>atE<nbsp>redhat.comE<gt>.

=cut
