=encoding UTF-8

=head1 NAME

gps - Documentation of collectd's C<gps plugin>

=head1 SYNOPSIS

LoadPlugin gps
<Plugin "gps">
  # Connect to localhost on gpsd regular port:
  Host "127.0.0.1"
  Port "2947"
  # 15 seconds timeout
  Timeout 15
  # Pause of 1 second between readings:
  Pause 1
</Plugin>


=head1 DESCRIPTION

The C<gps plugin> connects to gpsd on the host machine.
The host, port, timeout and pause are configurable. 

This is useful if you run an NTP server using a GPS for source and you want to
monitor it.

Mind your GPS must send $--GSA for having the data reported!

=head1 OPTIONS

=over 4

=item B<Host> I<Host>

The host on which gpsd runs. Defaults to B<localhost>.

=item B<Port> I<Port>

Port to connect to gpsd on the host machine. Defaults to B<2947>.

=item B<Timeout> I<Seconds>

Timeout in seconds (default 15 sec).

=item B<Pause> I<Seconds>

Pause to apply between readings in seconds (default 1 sec).

=back

=head1 NOTIFICATION DATA FORMAT

=over 4

=item B<satellites>

Number of satellites used for fix (type instance "used") and in view (type
instance "visible"). 0 means no GPS satellites are visible.

=item B<dilution_of_precision>

Vertical and horizontal dilution.
It should be between 0 and 3.
Look at the documentaiton of your GPS to know more.

=head1 SEE ALSO

L<collectd(1)>,
L<collectd.conf(5)>,
gpsd

=head1 AUTHOR

Nicolas JOURDEN E<lt>nicolas.jourden at laposte.netE<gt>

=cut
